# Generated by Django 6.0.6 on 2026-07-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=50, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('processor', models.CharField(blank=True, max_length=100)),
                ('ram_gb', models.PositiveIntegerField(blank=True, null=True)),
                ('storage_gb', models.PositiveIntegerField(blank=True, null=True)),
                ('battery_health', models.PositiveIntegerField(blank=True, help_text='Battery health percentage', null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('borrowed', 'Borrowed'), ('maintenance', 'Under Maintenance')], default='available', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('condition_notes', models.TextField(blank=True)),
            ],
        ),
    ]
